### PR TITLE
Adding REDIS support 

### PR DESCRIPTION
**Pull request by AndrewEastwood**
This is a part for the https://github.com/uthsc/UTHSC-WPCAS/pull/10
This will allow to use REDIS for storing active sessions.

### CODE REVIEW

**Comment by AndrewEastwood** [comment]
Hey @jfritschi! What do ya think about the PR?

**Comment by adamfranco** [comment]
Hi Andrew, thanks for this PR. I'll leave more review to @jfritschi, but just wanted to weigh in with a few thoughts:

Adding the full `predis-client` library to phpCAS repo may not be the best way to add this support as it will significantly bloat the phpCAS library for all users whether or not they use Redis for ticket storage (a narrow slice of the user-population).

Currently phpCAS doesn't have any dependencies on outside libraries or a required install process -- the `composer.json` was added mainly to allow phpCAS to be included by other projects rather than the other way around. If dependencies on other libraries are to be added to phpCAS and especially _optional_ dependencies like this PR introduces, then it may be good to take a step back and think about a phpCAS install / plugin process that allows users to optionally install additional dependencies to enable the features they wish to use, if any. 

This PR is introducing REDIS support for PGT storage, but there really isn't anything special about REDIS -- storage PGT storage back-ends that use MongoDB, Memcache, or any number of data-stores would be just as valid and it would be good to develop an implementation that allows these to be added cleanly without bloating either the code-base or the public API methods.

An alternate sort of implementation would be to refactor the PGT storage methods as we did with the `ProxiedService` system. Rather than adding arbitrary new API methods for every conceivable type of proxied service that one might need to call, we instead defined an interface for a [`CAS_ProxiedService`](https://github.com/Jasig/phpCAS/blob/master/source/CAS/ProxiedService.php) that users of phpCAS can implement as they need and pass into [`phpCAS::initializeProxiedService(CAS_ProxiedService $proxiedService)` system](https://github.com/Jasig/phpCAS/blob/master/source/CAS.php#L880-L901). A similar interface could be defined for PGT storage backends that would allow clients to implement arbitrary storage mechanisms that could then be wired into phpCAS with something like a `phpCAS::setPgtStorage(CAS_PgtStorage $pgtStorage)` call. Existing file & DB storage would be reworked to implement this new interface with the existing `setPGTStorageDb()` and `setPGTStorageFile()` methods reimplemented to create and set implementations of the new interface.

**Comment by AndrewEastwood** [comment]
So, @adamfranco, what do you recommend that we do with it?

**Comment by adamfranco** [comment]
I'd suggest first working up a PR with an interface and support for a pluggable PGT-Storage system as I described in the last paragraph above. This will be an easier feature to review, test, and support going forward and open up additional options for the Redis-specific feature you are looking for. The `CAS_PgtStorage` interface should define the only the methods that phpCAS will call on the instance passed into it.

Once pluggable PGT-Storage is in place, I see a few options for Redis support:

**Option 1: Maintain `CAS_PGTStorage_Redis` and `predis-client` it in your application, outside of phpCAS**

With `phpCAS::setPgtStorage(CAS_PgtStorage $pgtStorage)` you will no longer need to rely on patching phpCAS to wire-up this support.

**Option 2: Add your `CAS_PGTStorage_Redis` class and assume that `predis-client` can be autoloaded**

The `CAS_PGTStorage_Redis` class could simply assume that users of the class will need to have already added the `predis-client` library to their application and set it up to be autoloaded. This has the advantage of being simple in the phpCAS side and nothing will change for those that don't use the Redis support.

`predis-client` would then be added as a [suggested package](https://getcomposer.org/doc/04-schema.md#suggest) to phpCAS's `composer.json`. This would make it slightly clearer to those installing phpCAS via Composer that `predis-client` may be helpful for them to install if they want this feature.

**Option 3: Set up some other installation mechanism for dependent feature libraries**

Composer (or git submodules, or some build process) could be used to require all possible dependent libraries for any `CAS_PGTStorage` implementation shipped as part of phpCAS. This has the downside of adding these extra libraries to most installations whether they will be used or not, but would slightly lesson the steps required by those that do want to use them. This option is less desirable in my mind, but may make more sense if there are additional dependencies that are very commonly needed.

**Comment by AndrewEastwood** [comment]
gotcha

**Comment by jfritschi** [comment]
I really like adams options! There is not much to add from my side.

The current PR is really not the right way. We should not include code into phpcas that we are not developing/maintaining. This is what interfaces or packages are for. I also think this would be problematic due to the incompatible license.

**Comment by ikari7789** [comment]
I was also wanting to extract out the session management in this. Wouldn't it just be better to abstract out the session calls to classes that implement the SessionHandlerInterface and allow users to inject their own via the constructor (if none provided default to PHP's default session management)?

**Comment by jfritschi** [comment]
We already discussed something similar a while back in #42 . I guess this could be a good starting point for such an undertaking.

**Pull request closed without merging**
