### PR TITLE
Add function: let user can set base url

### PR DESCRIPTION
**Pull request by LeopardDennis**
Hi,

I'm using the phpCAS, it's amazing. Thank you. But sometimes the CAS server does not using the SSL. And the source code forced to use 'https'. So I need to customize the base url with 'http'. 

Hope your response.

### CODE REVIEW

**Comment by jfritschi** [comment]
Can you please explain why you would need a non-SSL CAS server? This is the worst thing you can do.

**Comment by LeopardDennis** [comment]
Caz the CAS server is not belong to me. And they just not using the SSL. 

In my opinion the phpCAS is a client. It needs to fit a variety of different circumstances. Am I right? 

Thanks.

**Comment by LeopardDennis** [comment]
@jfritschi How's that going?

**Comment by gboddin** [comment]
@jfritschi 

At first I'm hating this ...

After a second thinking, if you're using phpCAS over other networks than Internet (like Tor or i2p), it's acceptable to get http:// urls since the underlying transport take care of the encryption and setting up addtional SSL certificates would be tricky/impossible ( no CA in browsers for those network TLDs )...

@LeopardDennis if the CAS server is not those cases, I would really tell those people they're taking really high risks however.

**Comment by jfritschi** [comment]
I'm not convinced right now.

Even if you have transport encryption it breaks the concept of CAS in many ways: e.g. The cas client and also the user has to verify authenticity of the CAS server. That's why application level SSL it's part of the cas protocol.

A non SSL Cas server is simply broken on so many levels... Even supporting such a feature is madness in my eyes. 

Why should we support such (security) madness?

**Comment by LeopardDennis** [comment]
@gboddin I certainly know these risks. And I have told that to the cas server provider. But they use the cas in local network. All is under their controll. So I believe that is safety in some ways.

@jfritschi I reviewed the code. You guys determining whether 'base_url' is empty. But never let user to set it. So the program give the base_url a default value with 'https' forcely. I don't think this is good solution.

**Pull request merged**
